/** Declaration file generated by dts-gen */

export function getHoldemWinner(params: any, flags: any): any;

export function getOmahaWinner(params: any): any;

export function getType(set: any): any;

